// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using NetTopologySuite.Geometries;
using SQL_App;

namespace SQL_App.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20210705095648_initial")]
    partial class initial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.7")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("SQL_App.PolygonShape", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<Polygon>("Location")
                        .HasColumnType("geography");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Polygons");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Location = (NetTopologySuite.Geometries.Polygon)new NetTopologySuite.IO.WKTReader().Read("SRID=4326;POLYGON ((35.191766965947394 53.37158203124999, 33.02708758002874 51.21826171875, 33.44977658311846 55.06347656249999, 35.191766965947394 53.37158203124999))"),
                            Name = "Polygon01"
                        },
                        new
                        {
                            Id = 2,
                            Location = (NetTopologySuite.Geometries.Polygon)new NetTopologySuite.IO.WKTReader().Read("SRID=4326;POLYGON ((38.70265930723801 57.74414062500001, 37.09023980307208 57.568359375, 37.49229399862877 60.13916015625, 38.70265930723801 57.74414062500001))"),
                            Name = "Polygon02"
                        },
                        new
                        {
                            Id = 3,
                            Location = (NetTopologySuite.Geometries.Polygon)new NetTopologySuite.IO.WKTReader().Read("SRID=4326;POLYGON ((34.415973384481866 57.39257812499999, 31.89621446335144 55.37109374999999, 32.45415593941475 58.68896484375, 34.415973384481866 57.39257812499999))"),
                            Name = "Polygon03"
                        },
                        new
                        {
                            Id = 4,
                            Location = (NetTopologySuite.Geometries.Polygon)new NetTopologySuite.IO.WKTReader().Read("SRID=4326;POLYGON ((30.65681556429287 56.42578125, 28.70986084394286 53.72314453125, 30.164126343161097 59.19433593750001, 30.65681556429287 56.42578125))"),
                            Name = "Polygon04"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
